### ISSUE TITLE
Could this be packaged as a Chrome extension to make the change persistent?

### ISSUE THREAD

**Issue by markstos** [kfahy/slack-disable-wysiwyg-bookmarklet#12]
Asking for a friend.

**Comment by kfahy** [comment]
Yeah not a bad idea. I'd need to do some research to figure out how to make an extension, but if you'd like, feel free to make a repo and we can link to it from the README in this one. Or maybe we can add it to this repo too as an option.

**Comment by markstos** [comment]
Here's an example of providing the logic of "when the URL matches this pattern, run this bit of JavaScript":

https://developer.chrome.com/extensions/content_scripts

**Comment by Jerska** [comment]
If you go this route, please make it a WebExtension so that it works on FF too. ❤️

**Comment by rileytomasek** [comment]
@kfahy let me know if you have any questions with the extension and I'd be happy to help out.

Would you be cool if I integrated this into my Slack Chrome extension, [Tight](https://github.com/rileytomasek/tight/)? I realize that Tight is very opinionated, so it won't properly address this issue, but I think it's inline with the overall goals of Tight for people who are ok with everything else.

**Comment by kfahy** [comment]
@rileytomasek please do! Tight looks like an interesting extension. Feel free to copy the code over, and let me know if I can help with anything.

**Comment by pocc** [comment]
Done: https://github.com/pocc/no-wysiwyg

Firefox Addon: https://addons.mozilla.org/en-US/firefox/addon/disable-slack-wysiwyg/
Chrome Extn: Pending Review

Let me know if you want me to make any modifications to it.

**Comment by kfahy** [comment]
You're a hero, @pocc. Thanks as lot! I've added links to your repo and the Firefox addon in the readme, and will add it (or feel free to submit a PR) after Chrome is ready.

**Comment by pocc** [comment]
Will do. Thanks for making the script!
