### ISSUE TITLE
Another possible persistent desktop approach

### ISSUE THREAD

**Issue by kimsey0** [kfahy/slack-disable-wysiwyg-bookmarklet#16]
I'm still hoping that Slack will just add a setting for this, but if not, one could probably adopt this approach:
- https://medium.com/@dany74q/injecting-js-into-electron-apps-and-adding-rtl-support-for-microsoft-teams-d315dfb212a6
- https://github.com/dany74q/microsoft-teams-rtl-runner

**Comment by rickard-von-essen** [comment]
> I'm still hoping that Slack will just add a setting for this

FYI:

> We've started working on a preference that will let you return to the previous message composer. We don't have a specific release date to share right now — it's this team's top and only priority, however, and we expect to have it available on the desktop within a couple of weeks, with Android following shortly thereafter.

-- Slack support response

**Comment by kimsey0** [comment]
Yep, I got that response to my support request too. 😄
No reason to spend time on this, then.
