### ISSUE TITLE
Mention that this can be run in the desktop app too

### ISSUE THREAD

**Issue by d4rky-pl** [kfahy/slack-disable-wysiwyg-bookmarklet#4]
If you run the app with env var `SLACK_DEVELOPER_MENU` set to `true`, it'll allow you to open devtools in the desktop app and run this code snippet.

On Mac, it'll go like this:

```
SLACK_DEVELOPER_MENU=true /Applications/Slack.app/Contents/MacOS/Slack
```

not sure about other platforms :)

**Comment by adamralph** [comment]
And also mention how to run it, e.g.:

- from the hamburger menu top left, select View -> Developer -> Toggle WebApp DevTools
- select the Console tab
- paste the snippet in and hit enter

**Comment by johansatge** [comment]
👍 see #1

**Comment by d4rky-pl** [comment]
Duplicate of #1, closing :)
