### ISSUE TITLE
Activating this in Franz

### ISSUE THREAD

**Issue by adrianmcli** [kfahy/slack-disable-wysiwyg-bookmarklet#5]
I've figured out how to activate this in Franz, the Electron-based messaging aggregator tool.

1. Use the keyboard shortcut to open up the inspector:
   - Mac: <kbd>⌘ command</kbd> + <kbd>⌥ option</kbd> + <kbd>I</kbd>
   - Windows/Linux: <kbd>⌃ ctrl</kbd> + <kbd>⇧ shift</kbd> + <kbd>I</kbd>

2. Open up the console tab, and run the following to open up the current app's (i.e. Slack instance) dev console:

   ```js
   $(".app__service .is-active webview").openDevTools()
   ```

3. In the new window where this pops up, paste in the script from `index.js` without the `javascript:` prefix. Here's a simplified version (courtesy of https://github.com/kfahy/slack-disable-wysiwyg-bookmarklet/pull/3):

   ```js
   (_ => {
     const redux = slackDebug[slackDebug.activeTeamId].redux;
     const {wysiwyg_composer, wysiwyg_composer_ios, wysiwyg_composer_webapp, ...payload} = redux.getState().experiments;
     redux.dispatch({ type: '[19] Bulk add experiment assignments to redux', payload });
   })()
   ```

Should we document this as well?

**Comment by kfahy** [comment]
Oh nice find! I hadn't heard of Franz before - does it embed Slack's Electron app inside of its own Electron app?

Yeah this would be great to document. Please feel free to put up a PR, otherwise I'll take a look at Franz tonight and add the docs then. Thanks!

**Comment by adrianmcli** [comment]
Yeah it's one of many, but I think it's relatively popular. I'll work on that PR!
